"""
Django settings for django_cookiecutter project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
PROJECT_PATH = Path(__file__).resolve().parent.parent
BASE_DIR = PROJECT_PATH.parent

# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# Application definition

INSTALLED_APPS = [
    # Third party apps
    "django_extensions",
    "debug_toolbar",
    "treebeard",
    "sekizai",
    "easy_thumbnails",
    "mptt",
    # Django Apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    # Project apps
    "{{ django_cookiecutter.project_name }}",
    "{{ django_cookiecutter.project_name }}.contrib.users.apps.UsersConfig",
    # Django CMS Apps
    "cms",
    "menus",
    "djangocms_admin_style",
    "filer",
]

SITE_ID = 1
X_FRAME_OPTIONS = "SAMEORIGIN"

ROOT_URLCONF = "{{ django_cookiecutter.project_name }}.urls"

WSGI_APPLICATION = "{{ django_cookiecutter.project_name }}.wsgi.application"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = Path(BASE_DIR, "static")

# Media files
# https://docs.djangoproject.com/en/3.2/topics/files/

MEDIA_URL = "/media/"
MEDIA_ROOT = Path(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "users.User"
